services:
  # Frontend / Web Server
  frontend:
    container_name: portafolio-patrick
    image: patrick190/portafolio:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "8081:80"
    networks:
      - portafolio
    restart: always


networks:
  portafolio:
    external: true
    name: proxy-network
