# Generated by Django 6.1 on 2026-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='progreso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
